version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - /app/.next
      - .:/app
    restart: always
