version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - /app/.next
      - .:/app
    restart: always
    environment:
      DATABASE_URL: postgres://todoer:todoer@app-database/todoer
  app-database:
    image: postgres
    ports:
      - "35433:5432"
    environment:
      POSTGRES_DB: todoer
      POSTGRES_USER: todoer
      POSTGRES_PASSWORD: todoer
    volumes:
      - app-database:/var/lib/postgresql/data

volumes:
  app-database:
